spring:
  datasource:
    url: "SecretManagerのシークレットのARN"
    username: "SecretManagerのシークレットのARN"
    password: "SecretManagerのシークレットのARN"
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
